[build-system]
requires = [
    "setuptools",
    "wheel"
]

build-backend = "setuptools.build_meta"

# black configuration
[tool.black]
line-length = 100
target-version = [
    'py37',
    'py39'
]

# flake8 configuration
[flake8]
max-line-length = 100